project:
  type: website
  output-dir: "docs"

website:
  title: "Nangosyah Tom Wellard"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

